server:
   port: 8080
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.galaxy.mybatis.entity

spring:
  redis:
    host: localhost
    port: 6379
    password: Jq322401.
    timeout: 3000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/galaxy_db?characterEncoding=utf-8
    username: root
    password: "Jq322401."

upload:
  path: "/home/jixia/图片/user_images"